name: rick_and_morty_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  get_it: ^8.0.3
  drift: ^2.26.0
  path_provider: ^2.1.5
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.32
  shared_preferences: ^2.5.3

dev_dependencies:
  drift_dev: ^2.26.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true